language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t monkeyd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true monkeyd/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-766770920205"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"